In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.neighbors import KNeighborsRegressor

In [2]:
train = pd.read_csv("train_preprocessed.csv")
test = pd.read_csv("test_preprocessed.csv")

In [3]:
train.head()

,Unit_Accounting and Finance,Unit_Human Resource Management,Unit_IT,Unit_Logistics,Unit_Marketing,Unit_Operarions,Unit_Production,Unit_Purchasing,Unit_Quality,Unit_R&D,...,VAR3,VAR4,VAR5,VAR6,VAR7,Gender,Relationship_Status,Decision_skill_possess,Attrition_rate,Employee_ID
0,0,0,1,0,0,0,0,0,0,0,...,1.892105,0.184956,1.240340,-1.817683,-0.271674,1,0,3,0.1841,EID_23371
1,0,0,0,1,0,0,0,0,0,0,...,-0.452050,0.184956,0.175853,-1.817683,-0.271674,0,1,1,0.0670,EID_18000
2,0,0,0,0,0,0,0,0,1,0,...,-0.452050,2.150488,0.175853,0.766700,-0.271674,1,0,3,0.0851,EID_3891
3,0,1,0,0,0,0,0,0,0,0,...,-0.452050,0.184956,0.175853,-0.094761,-0.271674,1,1,0,0.0668,EID_17492
4,0,0,0,1,0,0,0,0,0,0,...,-0.452050,0.184956,-0.888634,0.766700,-1.360110,1,0,3,0.1827,EID_22534

In [4]:
train_X = train.drop(columns=['Employee_ID','Attrition_rate'])

In [5]:
train_X

,Unit_Accounting and Finance,Unit_Human Resource Management,Unit_IT,Unit_Logistics,Unit_Marketing,Unit_Operarions,Unit_Production,Unit_Purchasing,Unit_Quality,Unit_R&D,...,VAR1,VAR2,VAR3,VAR4,VAR5,VAR6,VAR7,Gender,Relationship_Status,Decision_skill_possess
0,0,0,1,0,0,0,0,0,0,0,...,1.095040,0.786163,1.892105,0.184956,1.240340,-1.817683,-0.271674,1,0,3
1,0,0,0,1,0,0,0,0,0,0,...,-0.107112,-1.011747,-0.452050,0.184956,0.175853,-1.817683,-0.271674,0,1,1
2,0,0,0,0,0,0,0,0,1,0,...,1.095040,-1.011747,-0.452050,2.150488,0.175853,0.766700,-0.271674,1,0,3
3,0,1,0,0,0,0,0,0,0,0,...,-0.107112,-1.910703,-0.452050,0.184956,0.175853,-0.094761,-0.271674,1,1,0
4,0,0,0,1,0,0,0,0,0,0,...,-2.511414,0.786163,-0.452050,0.184956,-0.888634,0.766700,-1.360110,1,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,0,0,0,0,0,1,0,0,0,0,...,-2.511414,0.786163,-0.452050,0.184956,0.175853,-0.094761,-0.271674,1,0,0
6996,0,0,0,0,0,0,0,0,0,1,...,-1.309263,-0.112792,-2.796205,0.184956,1.240340,0.766700,0.816763,1,0,1
6997,0,0,1,0,0,0,0,0,0,0,...,-1.309263,-0.112792,-0.452050,0.184956,1.240340,0.766700,-0.271674,1,1,2
6998,0,0,0,0,0,0,0,0,0,0,...,1.095040,0.786163,1.892105,0.184956,0.175853,-0.956222,-0.271674,1,0,0
6999,0,0,1,0,0,0,0,0,0,0,...,-0.107112,-0.112792,-1.624178,2.150488,1.240340,-1.817683,-0.271674,1,0,2

In [6]:
train_y = train['Attrition_rate']

In [7]:
train_X.isna().sum()

Unit_Accounting and Finance        0
Unit_Human Resource Management     0
Unit_IT                            0
Unit_Logistics                     0
Unit_Marketing                     0
Unit_Operarions                    0
Unit_Production                    0
Unit_Purchasing                    0
Unit_Quality                       0
Unit_R&D                           0
Unit_Sales                         0
Unit_Security                      0
Compensation_and_Benefits_type0    0
Compensation_and_Benefits_type1    0
Compensation_and_Benefits_type2    0
Compensation_and_Benefits_type3    0
Compensation_and_Benefits_type4    0
Age                                0
Time_of_service                    0
Time_since_promotion               0
growth_rate                        0
Post_Level                         0
Pay_Scale                          0
Work_Life_balance                  0
VAR1                               0
VAR2                               0
VAR3                               0
VAR4                               0
VAR5                               0
VAR6                               0
VAR7                               0
Gender                             0
Relationship_Status                0
Decision_skill_possess             0
dtype: int64

In [8]:
train_y.isna().sum()

0

In [9]:
sample = test[['Employee_ID','Attrition_rate']]
sample.to_csv("sample.csv", index = False)

In [10]:
sample.isna().sum()

Employee_ID          0
Attrition_rate    3000
dtype: int64

In [11]:
test_X = test.drop(columns=['Employee_ID','Attrition_rate'])

In [12]:
test_X.isna().sum()

Unit_Accounting and Finance        0
Unit_Human Resource Management     0
Unit_IT                            0
Unit_Logistics                     0
Unit_Marketing                     0
Unit_Operarions                    0
Unit_Production                    0
Unit_Purchasing                    0
Unit_Quality                       0
Unit_R&D                           0
Unit_Sales                         0
Unit_Security                      0
Compensation_and_Benefits_type0    0
Compensation_and_Benefits_type1    0
Compensation_and_Benefits_type2    0
Compensation_and_Benefits_type3    0
Compensation_and_Benefits_type4    0
Age                                0
Time_of_service                    0
Time_since_promotion               0
growth_rate                        0
Post_Level                         0
Pay_Scale                          0
Work_Life_balance                  0
VAR1                               0
VAR2                               0
VAR3                               0
VAR4                               0
VAR5                               0
VAR6                               0
VAR7                               0
Gender                             0
Relationship_Status                0
Decision_skill_possess             0
dtype: int64

In [13]:
def model_fit(model, train_X, train_y, test_X,sample_sub,filename):
    model.fit(train_X, train_y)
    train_pred = np.abs(model.predict(train_X))
    print("Train RMSE : ",mean_squared_error(train_y,train_pred,squared=False))
    test_pred = model.predict(test_X)
    sample['Attrition_rate'] = np.abs(test_pred)
    sample.to_csv(filename, index = False)
    return mean_squared_error(train_y,train_pred)

In [14]:
model = [LinearRegression(), Ridge(), Lasso(), ElasticNet(), KNeighborsRegressor()]

In [15]:
for i in model:
    print(i)
    model_fit(i, train_X, train_y, test_X, sample, str(i)[:-2]+".csv")

LinearRegression()
Train RMSE :  0.18510218392406927
Ridge()
Train RMSE :  0.18510000691582498
Lasso()

<ipython-input-13-1892ff7c040d>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['Attrition_rate'] = np.abs(test_pred)
<ipython-input-13-1892ff7c040d>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['Attrition_rate'] = np.abs(test_pred)
<ipython-input-13-1892ff7c040d>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['Attrition_rate'] = np.abs(test_pred)
<ipython-input-13-1892ff7c040d>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['Attrition_rate'] = np.abs(test_pred)

Train RMSE :  0.18574000922221678
ElasticNet()
Train RMSE :  0.18574000922221678
KNeighborsRegressor()
Train RMSE :  0.1647796292678714

<ipython-input-13-1892ff7c040d>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['Attrition_rate'] = np.abs(test_pred)

In [16]:
res = []
for i in range(1,10):
    model = KNeighborsRegressor(n_neighbors=i)
    print(i)
    err = model_fit(model, train_X, train_y, test_X, sample, str(i)+"KNN.csv")
    res.append(err)

1
Train RMSE :  0.0

<ipython-input-13-1892ff7c040d>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['Attrition_rate'] = np.abs(test_pred)

2
Train RMSE :  0.12961839707111683

<ipython-input-13-1892ff7c040d>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['Attrition_rate'] = np.abs(test_pred)

3
Train RMSE :  0.150289843817216

<ipython-input-13-1892ff7c040d>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['Attrition_rate'] = np.abs(test_pred)

4
Train RMSE :  0.15959414990117457

<ipython-input-13-1892ff7c040d>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['Attrition_rate'] = np.abs(test_pred)

5
Train RMSE :  0.1647796292678714

<ipython-input-13-1892ff7c040d>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['Attrition_rate'] = np.abs(test_pred)

6
Train RMSE :  0.1683585381204516

<ipython-input-13-1892ff7c040d>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['Attrition_rate'] = np.abs(test_pred)

7
Train RMSE :  0.17067913277632085

<ipython-input-13-1892ff7c040d>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['Attrition_rate'] = np.abs(test_pred)

8
Train RMSE :  0.17247035348166154

<ipython-input-13-1892ff7c040d>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['Attrition_rate'] = np.abs(test_pred)

9
Train RMSE :  0.17421374756320934

<ipython-input-13-1892ff7c040d>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['Attrition_rate'] = np.abs(test_pred)