In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_log_error

In [2]:
train = pd.read_csv("train_preprocessed.csv")
test = pd.read_csv("test_preprocessed.csv")
sample = pd.read_csv("sample_submission.csv")

In [3]:
train.head()

,Loyalty_customer_No,Loyalty_customer_Yes,Product_Category_Child_care,Product_Category_Cosmetics,Product_Category_Educational,Product_Category_Fashion,Product_Category_Home_decor,Product_Category_Hospitality,Product_Category_Organic,Product_Category_Pet_care,...,Market_Category,Demand,charges_1,charges in percentage,Minimum_price,Maximum_price,Grade,Discount_avail,Selling_Price,Product_id
0,0,1,0,0,0,1,0,0,0,0,...,-1.155956,0.602814,0.900658,0.175721,-0.236982,-0.449692,1,0.0,4185.947700,BRAE2NF6JA5GUEXG
1,0,1,0,0,0,1,0,0,0,0,...,-1.026374,0.014897,1.070979,0.411432,1.830033,1.114280,0,0.0,9271.490256,TUNE8SFB6RJN2HSD
2,0,1,1,0,0,0,0,0,0,0,...,1.465136,-1.403020,-0.121271,-0.295700,1.031538,0.270306,0,0.0,6785.701362,BRAEAR7WZPQGPBZU
3,0,1,0,0,1,0,0,0,0,0,...,-1.032264,-0.088853,-0.980988,0.647143,0.728266,4.015907,2,0.0,13028.917824,WATDZ2ZQ8JPDHCTJ
4,0,1,0,0,0,0,0,0,0,0,...,-0.796660,-0.538436,-0.437582,-1.474253,-0.490320,0.811692,1,1.0,906.553935,JWSEBUKYQPMBZ3RK

In [4]:
train_X = train.drop(columns=['Product_id','Selling_Price'])

In [5]:
train_X

,Loyalty_customer_No,Loyalty_customer_Yes,Product_Category_Child_care,Product_Category_Cosmetics,Product_Category_Educational,Product_Category_Fashion,Product_Category_Home_decor,Product_Category_Hospitality,Product_Category_Organic,Product_Category_Pet_care,...,Product_Category_Technology,Stall_no,Market_Category,Demand,charges_1,charges in percentage,Minimum_price,Maximum_price,Grade,Discount_avail
0,0,1,0,0,0,1,0,0,0,0,...,0,0.806981,-1.155956,0.602814,0.900658,0.175721,-0.236982,-0.449692,1,0.0
1,0,1,0,0,0,1,0,0,0,0,...,0,0.876679,-1.026374,0.014897,1.070979,0.411432,1.830033,1.114280,0,0.0
2,0,1,1,0,0,0,0,0,0,0,...,0,-1.144580,1.465136,-1.403020,-0.121271,-0.295700,1.031538,0.270306,0,0.0
3,0,1,0,0,1,0,0,0,0,0,...,0,1.713062,-1.032264,-0.088853,-0.980988,0.647143,0.728266,4.015907,2,0.0
4,0,1,0,0,0,0,0,0,0,0,...,0,-1.283977,-0.796660,-0.538436,-0.437582,-1.474253,-0.490320,0.811692,1,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6322,0,1,0,0,0,0,0,0,0,0,...,1,-0.586991,-1.026374,-0.123436,2.830968,-0.059989,2.141093,1.367777,0,0.0
6323,0,1,1,0,0,0,0,0,0,0,...,0,-0.308197,-0.843781,-0.538436,0.032830,-1.238542,0.029183,-0.392281,0,0.0
6324,1,0,0,0,0,0,0,0,0,0,...,0,0.737282,0.940917,-0.745936,0.146377,-1.709963,0.825845,2.296342,3,0.0
6325,0,1,0,0,0,0,0,0,0,0,...,0,0.109995,1.494586,-1.472186,0.016609,-1.709963,0.381931,-0.134624,0,0.0
6326,0,1,0,0,0,0,0,0,0,0,...,1,-1.005183,-0.826111,1.501981,2.830968,-0.767121,0.217468,-0.263868,0,0.0

In [6]:
train.head()

,Loyalty_customer_No,Loyalty_customer_Yes,Product_Category_Child_care,Product_Category_Cosmetics,Product_Category_Educational,Product_Category_Fashion,Product_Category_Home_decor,Product_Category_Hospitality,Product_Category_Organic,Product_Category_Pet_care,...,Market_Category,Demand,charges_1,charges in percentage,Minimum_price,Maximum_price,Grade,Discount_avail,Selling_Price,Product_id
0,0,1,0,0,0,1,0,0,0,0,...,-1.155956,0.602814,0.900658,0.175721,-0.236982,-0.449692,1,0.0,4185.947700,BRAE2NF6JA5GUEXG
1,0,1,0,0,0,1,0,0,0,0,...,-1.026374,0.014897,1.070979,0.411432,1.830033,1.114280,0,0.0,9271.490256,TUNE8SFB6RJN2HSD
2,0,1,1,0,0,0,0,0,0,0,...,1.465136,-1.403020,-0.121271,-0.295700,1.031538,0.270306,0,0.0,6785.701362,BRAEAR7WZPQGPBZU
3,0,1,0,0,1,0,0,0,0,0,...,-1.032264,-0.088853,-0.980988,0.647143,0.728266,4.015907,2,0.0,13028.917824,WATDZ2ZQ8JPDHCTJ
4,0,1,0,0,0,0,0,0,0,0,...,-0.796660,-0.538436,-0.437582,-1.474253,-0.490320,0.811692,1,1.0,906.553935,JWSEBUKYQPMBZ3RK

In [7]:
train['Product_id'].value_counts()

TOPEATNAAKXFBCCP    1
PACEB9TYMS5FEHHY    1
RNGE87FCBXPY8UU9    1
BKPEGZCFYTJXMRGY    1
CRTECN2QZZ9WFURB    1
                   ..
MUGEAGGKPUYPSZAG    1
NKCE9G2AFPSFBUBS    1
SHIE7DFN8MFZKQUR    1
NKCECZPZCAHUVVMG    1
MUGE6ZDZRGWDC9NF    1
Name: Product_id, Length: 6327, dtype: int64

In [8]:
train_y = train['Selling_Price']

In [9]:
train_X.isna().sum()

Loyalty_customer_No             0
Loyalty_customer_Yes            0
Product_Category_Child_care     0
Product_Category_Cosmetics      0
Product_Category_Educational    0
Product_Category_Fashion        0
Product_Category_Home_decor     0
Product_Category_Hospitality    0
Product_Category_Organic        0
Product_Category_Pet_care       0
Product_Category_Repair         0
Product_Category_Technology     0
Stall_no                        0
Market_Category                 0
Demand                          0
charges_1                       0
charges in percentage           0
Minimum_price                   0
Maximum_price                   0
Grade                           0
Discount_avail                  0
dtype: int64

In [10]:
train_y.isna().sum()

0

In [11]:
sample = test[['Product_id','Selling_Price']]
sample.to_csv("sample.csv", index = False)

In [12]:
sample.isna().sum()

Product_id          0
Selling_Price    3430
dtype: int64

In [13]:
test_X = test.drop(columns=['Product_id','Selling_Price'])

In [14]:
test_X.isna().sum()

Loyalty_customer_No             0
Loyalty_customer_Yes            0
Product_Category_Child_care     0
Product_Category_Cosmetics      0
Product_Category_Educational    0
Product_Category_Fashion        0
Product_Category_Home_decor     0
Product_Category_Hospitality    0
Product_Category_Organic        0
Product_Category_Pet_care       0
Product_Category_Repair         0
Product_Category_Technology     0
Stall_no                        0
Market_Category                 0
Demand                          0
charges_1                       0
charges in percentage           0
Minimum_price                   0
Maximum_price                   0
Grade                           0
Discount_avail                  0
dtype: int64

In [15]:
def model_fit(model, train_X, train_y, test_X,sample_sub,filename):
    model.fit(train_X, train_y)
    train_pred = np.abs(model.predict(train_X))
    print("Train RMSE : ",mean_squared_error(train_y,train_pred,squared=False))
    test_pred = model.predict(test_X)
    sample['Selling_Price'] = np.abs(test_pred)
    sample.to_csv(filename, index = False)
    return mean_squared_error(train_y,train_pred)

In [16]:
model = [LinearRegression(), Ridge(), Lasso(), ElasticNet(), KNeighborsRegressor()]

In [17]:
for i in model:
    print(i)
    model_fit(i, train_X, train_y, test_X, sample, str(i)[:-2]+".csv")

LinearRegression()
Train RMSE :  931.5697387068743
Ridge()
Train RMSE :  931.7931143024099
Lasso()
Train RMSE :  932.080351252647
ElasticNet()
Train RMSE :  1668.7781457754875
KNeighborsRegressor()

<ipython-input-15-03ca30967a90>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['Selling_Price'] = np.abs(test_pred)
<ipython-input-15-03ca30967a90>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['Selling_Price'] = np.abs(test_pred)
<ipython-input-15-03ca30967a90>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['Selling_Price'] = np.abs(test_pred)
<ipython-input-15-03ca30967a90>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['Selling_Price'] = np.abs(test_pred)

Train RMSE :  1322.0388059834768

<ipython-input-15-03ca30967a90>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['Selling_Price'] = np.abs(test_pred)

In [18]:
res = []
for i in range(1,10):
    model = KNeighborsRegressor(n_neighbors=i)
    print(i)
    err = model_fit(model, train_X, train_y, test_X, sample, str(i)+"KNN.csv")
    res.append(err)

1
Train RMSE :  399.46337309703824

<ipython-input-15-03ca30967a90>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['Selling_Price'] = np.abs(test_pred)

2
Train RMSE :  971.8135278203528

<ipython-input-15-03ca30967a90>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['Selling_Price'] = np.abs(test_pred)

3
Train RMSE :  1174.2186504049698

<ipython-input-15-03ca30967a90>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['Selling_Price'] = np.abs(test_pred)

4
Train RMSE :  1256.9644222100533

<ipython-input-15-03ca30967a90>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['Selling_Price'] = np.abs(test_pred)

5
Train RMSE :  1322.0388059834768

<ipython-input-15-03ca30967a90>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['Selling_Price'] = np.abs(test_pred)

6
Train RMSE :  1372.1262312886884

<ipython-input-15-03ca30967a90>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['Selling_Price'] = np.abs(test_pred)

7
Train RMSE :  1399.198683350974

<ipython-input-15-03ca30967a90>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['Selling_Price'] = np.abs(test_pred)

8
Train RMSE :  1432.4918092774053

<ipython-input-15-03ca30967a90>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['Selling_Price'] = np.abs(test_pred)

9
Train RMSE :  1458.425908592649

<ipython-input-15-03ca30967a90>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['Selling_Price'] = np.abs(test_pred)